---
#
# Installing Filebeat
#

# Install Filebeat 

- name: Install Filebeat with apt
  apt:
   name: filebeat
   update_cache: yes
 
# Replace Filebeat configuration to ship to Logz.io. 

- name: Replace default filebeat.yml configurations
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
  notify:
    - restart filebeat

# Starting Filebeat

- name: Starting Filebeat
  service:
   name: filebeat
   state: started
