----
#
# Install Java 
#
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes 
    
- name: Install java 8 requirements
    apt: name=python-software-properties

  - name: Add Java 8 repository
    apt_repository: repo='ppa:webupd8team/java'

  - name: Agree to oracle license
    debconf: name=oracle-java8-installer question=shared/accepted-oracle-license-v1-1 vtype=select value=true

  - name: Install Java 8
    apt: name=oracle-java8-installer force=yes
